from pathlib import Path

import Gaffer

import GafferScatterPlus


def _documentation_url(page_name):
    path = Path(__file__).resolve().parents[2] / "docs" / "html" / page_name
    return path.as_uri() if path.exists() else None


if GafferScatterPlus.ScatterPlus is not None:
    Gaffer.Metadata.registerNode(
        GafferScatterPlus.ScatterPlus,
        "description",
        "Clarisse-style scatter wrapper that generates helper points and an instanced result branch from support geometry, prototype scenes, and an optional image input.",
        "documentation:url",
        lambda node: _documentation_url("ScatterPlus.html"),
        "layout:activator:isRandomPrototypeMode",
        lambda node: node["prototypeMode"].getValue() == 1,
        "layout:activator:isIndexPrototypeMode",
        lambda node: node["prototypeMode"].getValue() == 3,
        "layout:activator:hasImageDistribution",
        lambda node: node["distribution"].getValue() == 2,
        "layout:activator:isQuantizedVarianceMode",
        lambda node: node["varianceMode"].getValue() == 1,
        plugs={
            "outputLocation": ["description", "Root location for helper points and instance branches.", "layout:section", "Output"],
            "pointType": ["description", "Helper point type written to the points branch.", "layout:section", "Output"],
            "support": ["description", "Filter used to find support geometry for sampling.", "layout:section", "Support"],
            "image": ["description", "Optional density or prototype-selection image input.", "layout:section", "Support"],
            "densityPrimitiveVariable": ["description", "Support primitive variable sampled for density/decimation and written to helper points using this name.", "layout:section", "Support"],
            "referencePosition": ["description", "Name used for generated reference-position points primvar, populated from the support reference frame when available.", "layout:section", "Support"],
            "uv": ["description", "Support UV primitive variable used for image-driven scatter.", "layout:section", "Support"],
            "distribution": [
                "description", "Support point sampling mode.",
                "preset:Random", 0,
                "preset:Primitive Center", 1,
                "preset:Image", 2,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Support",
            ],
            "density": ["description", "Global density multiplier applied during point generation.", "layout:section", "Support"],
            "pointCount": ["description", "Base count for random or image-driven helper-point generation.", "layout:section", "Support"],
            "seed": ["description", "Deterministic seed for helper points and prototype assignment.", "layout:section", "Support"],
            "jittering": ["description", "Support point offset jitter used during helper point generation.", "layout:section", "Support"],
            "prototypeRoots": ["description", "Space-separated prototype root filter for the prototypes input scene.", "layout:section", "Prototypes"],
            "prototypeRootsList": ["description", "Optional explicit list of prototype root filters.", "layout:section", "Prototypes"],
            "prototypeMode": [
                "description", "How prototypes are assigned to generated instances.",
                "preset:First", 0,
                "preset:Random", 1,
                "preset:Cycle", 2,
                "preset:Index", 3,
                "preset:ID Primitive Variable", 4,
                "preset:Luminance", 5,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Prototypes",
            ],
            "prototypeIndex": ["description", "Fixed prototype index used by Index mode.", "layout:section", "Prototypes", "layout:activator", "isIndexPrototypeMode"],
            "idVariable": ["description", "Support primitive variable name sampled for ID-driven prototype selection and written to helper points.", "layout:section", "Prototypes"],
            "geometryIdAttribute": ["description", "Prototype attribute name used to resolve geometry IDs.", "layout:section", "Prototypes"],
            "probabilityAttribute": ["description", "Prototype attribute name used for weighted random assignment.", "layout:section", "Prototypes"],
            "position": ["description", "Base position offset applied to each instance.", "layout:section", "Transform"],
            "orientation": ["description", "Base orientation offset in degrees.", "layout:section", "Transform"],
            "scale": ["description", "Base instance scale.", "layout:section", "Transform"],
            "rotationOrder": [
                "description", "Euler rotation order used for orientation composition.",
                "preset:XYZ", 0,
                "preset:XZY", 1,
                "preset:YXZ", 2,
                "preset:YZX", 3,
                "preset:ZXY", 4,
                "preset:ZYX", 5,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Transform",
            ],
            "useSupportNormals": ["description", "Align generated instances to sampled support normals.", "layout:section", "Transform"],
            "varianceMode": [
                "description", "Continuous or stepped variance behaviour.",
                "preset:Continuous", 0,
                "preset:Quantized", 1,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Variance",
            ],
            "positionVariance": ["description", "Random position offset range.", "layout:section", "Variance"],
            "positionVarianceStep": ["description", "Position variance quantization step.", "layout:section", "Variance", "layout:activator", "isQuantizedVarianceMode"],
            "rotationVariance": ["description", "Random rotation offset range in degrees.", "layout:section", "Variance"],
            "rotationVarianceStep": ["description", "Rotation variance quantization step.", "layout:section", "Variance", "layout:activator", "isQuantizedVarianceMode"],
            "scaleVariance": ["description", "Random scale offset range.", "layout:section", "Variance"],
            "scaleVarianceStep": ["description", "Scale variance quantization step.", "layout:section", "Variance", "layout:activator", "isQuantizedVarianceMode"],
            "uniformScaleVariance": ["description", "Use one scalar random offset for XYZ scale variation.", "layout:section", "Variance"],
            "timeOffset": ["description", "Base time offset stored on scattered instances.", "layout:section", "Time"],
            "timeVariance": ["description", "Random time offset range.", "layout:section", "Time"],
            "timeVarianceSamples": ["description", "Number of discrete buckets used when quantizing time variance offsets.", "layout:section", "Time"],
            "supportSpace": [
                "description", "Reference space used when generating support points. Reference mode evaluates the support at frame 0.",
                "preset:Object", 0,
                "preset:World", 1,
                "preset:Reference", 2,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Advanced",
            ],
            "referenceFrame": ["description", "Frame used when support or decimation evaluation is set to Reference.", "layout:section", "Advanced"],
            "decimationSpace": [
                "description", "Reference space used for seeded procedural decimation and collision evaluation. Reference mode evaluates the support at frame 0.",
                "preset:Object", 0,
                "preset:World", 1,
                "preset:Reference", 2,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Advanced",
            ],
            "collisionMode": [
                "description", "Optional collision rejection mode.",
                "preset:Off", 0,
                "preset:Bounds", 1,
                "preset:Ellipsoid", 2,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Advanced",
            ],
            "collisionScaleMultiplier": ["description", "Scales evaluation bounds used for simple collision rejection.", "layout:section", "Advanced"],
            "collisionDetectionOrder": [
                "description", "Order used before collision rejection.",
                "preset:Generated", 0,
                "preset:Random", 1,
                "plugValueWidget:type", "GafferUI.PresetsPlugValueWidget",
                "layout:section", "Advanced",
            ],
            "collisionSeed": ["description", "Seed used by random collision ordering.", "layout:section", "Advanced"],
            "decimationSeed": ["description", "Seed used by procedural threshold decimation when no image-driven decimation score is present.", "layout:section", "Advanced"],
            "decimateValue": ["description", "Threshold used to reject instances from image-driven or seeded procedural decimation scores.", "layout:section", "Advanced"],
        },
    )
