import os
from pathlib import Path

import Gaffer

import GafferScatterPaint
import GafferSceneUI
import GafferScatterPaintUI
import GafferScatterPaintUI.paintedPointsPanel


_plugin_root = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
_tool_icon = os.path.join(
    _plugin_root,
    "graphics",
    "gafferScatterPaintUIPaintPointsTool.png",
)


def _documentation_url(page_name):
    path = Path(_plugin_root) / "docs" / "html" / page_name
    return path.as_uri() if path.exists() else None


Gaffer.Metadata.registerNode(
    GafferScatterPaint.PaintedPoints,
    "description",
    "Authoritative authored-data node for scatter paint layers and strokes.",
    "documentation:url",
    lambda node: _documentation_url("PaintedPoints.html"),
    "layout:section:Authoring:collapsed",
    False,
    "layout:section:Cache:collapsed",
    False,
    "layout:customWidget:authoringData:widgetType",
    "GafferScatterPaintUI.paintedPointsPanel.PaintedPointsAuthoringWidget",
    "layout:customWidget:authoringData:section",
    "Authoring",
    "layout:customWidget:authoringData:index",
    -1,
    "layout:customWidget:cacheData:widgetType",
    "GafferScatterPaintUI.paintedPointsPanel.PaintedPointsCacheWidget",
    "layout:customWidget:cacheData:section",
    "Cache",
    "layout:customWidget:cacheData:index",
    -1,
    plugs={
        "surfaceMode": [
            "description",
            "Surface basis used for authoring and later attachment evaluation.",
            "preset:Viewport Mesh",
            0,
            "preset:Pre-Subdiv Cage",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "paintThroughMode": [
            "description",
            "Controls whether painting hits only the front-most surface or the filtered brush volume.",
            "preset:Front Most Only",
            0,
            "preset:Filtered Brush Volume",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "relaxObjective": [
            "description",
            "Controls whether Relax preserves the current silhouette or redistributes selected points more evenly.",
            "preset:Preserve Silhouette",
            0,
            "preset:Even Redistribution",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "targetFilter": [
            "description",
            "Location filter used to constrain paint targets.",
        ],
        "targetSetFilter": [
            "description",
            "Set-expression filter used to constrain paint targets.",
        ],
        "cacheMode": [
            "description",
            "Chooses whether authored data is stored embedded in the node or in an external cache file.",
            "preset:Embedded",
            0,
            "preset:External",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "cachePath": [
            "description",
            "External cache path when cache mode is set to External.",
        ],
        "cachePathMode": [
            "description",
            "Defines how relative cache paths should be resolved.",
            "preset:Absolute",
            0,
            "preset:Relative To Script",
            1,
            "preset:Relative To Project",
            2,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "projectRoot": [
            "description",
            "Project root used when cache paths are resolved relative to the project.",
        ],
        "lockMode": [
            "description",
            "Write-locking policy for cache edits.",
            "preset:Session Aware",
            0,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "backupEnabled": [
            "description",
            "Enables optional backup creation during destructive cache operations.",
        ],
        "backupPolicy": [
            "description",
            "Controls whether backup files are written during cache operations.",
            "preset:Off",
            0,
            "preset:On",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "compactionMode": [
            "description",
            "Compaction behavior after cache edits.",
            "preset:Immediate Blocking",
            0,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "globalModePrecedence": [
            "description",
            "Controls whether stroke or layer mode overrides win when both are present.",
            "preset:Stroke Wins",
            0,
            "preset:Layer Wins",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "pressureDefaults": [
            "description",
            "Default pressure handling used by paint strokes.",
        ],
        "pressureDefaults.enabled": [
            "description",
            "Enables pressure-sensitive brush behavior.",
        ],
        "pressureDefaults.mappingMode": [
            "description",
            "Selects direct or curve-driven pressure mapping.",
            "preset:Direct",
            0,
            "preset:Curve",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "pressureDefaults.densityCurve": [
            "description",
            "Stored density response curve used when pressure mapping mode is set to Curve.",
        ],
        "pressureDefaults.softnessCurve": [
            "description",
            "Stored softness response curve used when pressure mapping mode is set to Curve.",
        ],
        "brushDefaults": [
            "description",
            "Default brush settings used when the paint tool is activated.",
        ],
        "brushDefaults.size": [
            "description",
            "Default brush radius.",
        ],
        "brushDefaults.points": [
            "description",
            "Default point count spawned per paint dab before density scaling.",
        ],
        "brushDefaults.density": [
            "description",
            "Default relative point density.",
        ],
        "brushDefaults.softness": [
            "description",
            "Default brush falloff softness.",
        ],
        "brushDefaults.spacing": [
            "description",
            "Default spacing between brush dabs.",
        ],
        "brushDefaults.rotationMode": [
            "description",
            "Default brush rotation/randomization mode used for authored point orientation behavior.",
        ],
        "brushDefaults.scaleJitter": [
            "description",
            "Default random scale variation.",
        ],
        "brushDefaults.widthJitter": [
            "description",
            "Default random width variation.",
        ],
        "defaultColor": [
            "description",
            "Default authored color used when no layer, stroke, or point override is present.",
        ],
        "layers": [
            "description",
            "Authored layer list mirrored from the scatter-paint cache for UI inspection and state synchronization.",
        ],
        "selectionSets": [
            "description",
            "Named point-selection sets mirrored from the scatter-paint cache for UI inspection and recall.",
        ],
        "cacheBlob": [
            "description",
            "Embedded scatter-paint cache blob used when cache mode is set to Embedded.",
        ],
        "validationSummary": [
            "description",
            "Human-readable summary of cache validation, topology, and attachment state.",
        ],
        "cacheResolvedPath": [
            "description",
            "Resolved external cache path after applying the current cache path mode.",
        ],
    },
)

Gaffer.Metadata.registerNode(
    GafferScatterPaint.AttachedPoints,
    "description",
    "Evaluates authored scatter paint anchors against the input scene.",
    "documentation:url",
    lambda node: _documentation_url("AttachedPoints.html"),
    plugs={
        "points": [
            "description",
            "Connection to the authored scatter paint node.",
        ],
        "outputLocation": [
            "description",
            "Scene location for the evaluated points output.",
        ],
        "pointType": [
            "description",
            "Requested output primitive type for the evaluated scatter points.",
        ],
        "includeAttributes": [
            "description",
            "Comma-separated optional output attributes to include when exportPreset is set to Custom.",
        ],
        "exportPreset": [
            "description",
            "Selects whether AttachedPoints outputs guaranteed attributes only, all optional attachment attrs, or a custom optional subset.",
            "preset:Minimal",
            0,
            "preset:Full",
            1,
            "preset:Custom",
            2,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "surfaceSolveMode": [
            "description",
            "Surface solve strategy used to resolve authored anchors against the current scene.",
            "preset:Hybrid",
            0,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
        ],
        "allowCrossMeshReproject": [
            "description",
            "Allows unresolved attachments to try fallback reprojection behavior across compatible mesh targets when direct triangle attachment cannot be resolved.",
        ],
        "keepLastValidOutput": [
            "description",
            "Preserves the most recent valid solve result so it can be reused when a later solve becomes invalid or unresolved.",
        ],
        "strictUnresolved": [
            "description",
            "Treats unresolved attachments as a solve error while still reporting diagnostics and optionally reusing the last valid output when enabled.",
        ],
        "debugColor": [
            "description",
            "Displays attachment debug colors in `Cs` while keeping authored color in `scatterColor`.",
        ],
        "resolvedPointCount": [
            "description",
            "Number of authored points currently resolved by the attachment solve.",
        ],
        "unresolvedPointCount": [
            "description",
            "Number of authored points that remain unresolved after the attachment solve.",
        ],
        "validationCategories": [
            "description",
            "Validation categories reported by the solve node.",
        ],
        "solveStatus": [
            "description",
            "Human-readable solve summary derived from the connected authored data.",
        ],
    },
)

Gaffer.Metadata.registerNode(
    GafferScatterPaint.StaticPoints,
    "description",
    "Holds baked static point output generated from authored scatter paint data.",
    "documentation:url",
    lambda node: _documentation_url("StaticPoints.html"),
    plugs={
        "debugColor": [
            "description",
            "Displays attachment debug colors in `Cs` while keeping authored color in `scatterColor`.",
        ],
    },
)

Gaffer.Metadata.registerNode(
    GafferScatterPaintUI.PaintPointsTool,
    "description",
    "SceneView scatter-paint tool for paint, erase, selection, relax, reproject, layer editing, and stroke editing.",
    "documentation:url",
    lambda node: _documentation_url("PaintPointsTool.html"),
    "nodeToolbar:bottom:type",
    "GafferUI.StandardNodeToolbar.bottom",
    "nodeToolbar:right:type",
    "GafferUI.StandardNodeToolbar.right",
    "viewer:shortCut",
    "B",
    "viewer:shouldAutoActivate",
    False,
    "order",
    9,
    "toolbarLayout:activator:isPaint",
    lambda node: node["mode"].getValue() == 0,
    "toolbarLayout:activator:isErase",
    lambda node: node["mode"].getValue() == 1,
    "toolbarLayout:activator:isSelectBrush",
    lambda node: node["mode"].getValue() == 2,
    "toolbarLayout:activator:isSelectLasso",
    lambda node: node["mode"].getValue() == 3,
    "toolbarLayout:activator:isRelax",
    lambda node: node["mode"].getValue() == 4,
    "toolbarLayout:activator:isReproject",
    lambda node: node["mode"].getValue() == 5,
    "toolbarLayout:activator:isLayerEdit",
    lambda node: node["mode"].getValue() == 6,
    "toolbarLayout:activator:isStrokeEdit",
    lambda node: node["mode"].getValue() == 7,
    "toolbarLayout:activator:usesBrushRadius",
    lambda node: node["mode"].getValue() in (0, 1, 2, 4, 5),
    "toolbarLayout:activator:usesBrushFalloff",
    lambda node: node["mode"].getValue() in (0, 1),
    "toolbarLayout:activator:usesBrushSpacing",
    lambda node: node["mode"].getValue() in (0, 1, 2, 4, 5),
    "toolbarLayout:activator:usesTargetFilters",
    lambda node: node["mode"].getValue() in (0, 1, 5),
    "toolbarLayout:activator:usesSurfaceMode",
    lambda node: node["mode"].getValue() in (0, 1, 5),
    "toolbarLayout:activator:usesPressure",
    lambda node: node["mode"].getValue() == 0,
    "toolbarLayout:activator:layerRename",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 0
    ),
    "toolbarLayout:activator:layerSetVisible",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 1
    ),
    "toolbarLayout:activator:layerSetMute",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 2
    ),
    "toolbarLayout:activator:layerSetSolo",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 3
    ),
    "toolbarLayout:activator:layerSetTimeRange",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 4
    ),
    "toolbarLayout:activator:layerMove",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 5
    ),
    "toolbarLayout:activator:layerSetMode",
    lambda node: (
        node["mode"].getValue() == 6 and node["layerEditAction"].getValue() == 6
    ),
    "toolbarLayout:activator:strokeRename",
    lambda node: (
        node["mode"].getValue() == 7 and node["strokeEditAction"].getValue() == 0
    ),
    "toolbarLayout:activator:strokeMove",
    lambda node: (
        node["mode"].getValue() == 7 and node["strokeEditAction"].getValue() == 2
    ),
    "toolbarLayout:activator:strokeMerge",
    lambda node: (
        node["mode"].getValue() == 7 and node["strokeEditAction"].getValue() == 3
    ),
    plugs={
        "mode": [
            "description",
            "Selects the current painting, selection, relax, reproject, layer-edit, or stroke-edit interaction mode.",
            "preset:Paint",
            0,
            "preset:Erase",
            1,
            "preset:SelectBrush",
            2,
            "preset:SelectLasso",
            3,
            "preset:Relax",
            4,
            "preset:Reproject",
            5,
            "preset:LayerEdit",
            6,
            "preset:StrokeEdit",
            7,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Mode",
            "toolbarLayout:section",
            "Bottom",
            "toolbarLayout:width",
            120,
        ],
        "targetNode": [
            "description",
            "Optional relative node path to the PaintedPoints node targeted by the tool. Leave empty to resolve the target automatically from focus or selection.",
            "layout:visibilityActivator",
            False,
        ],
        "layerName": [
            "description",
            "Name used by LayerEdit when renaming the selected layer.",
            "label",
            "Layer Name",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            150,
            "toolbarLayout:visibilityActivator",
            "layerRename",
        ],
        "strokeName": [
            "description",
            "Name used by StrokeEdit when renaming the selected stroke.",
            "label",
            "Stroke Name",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            150,
            "toolbarLayout:visibilityActivator",
            "strokeRename",
        ],
        "strokeEditAction": [
            "description",
            "StrokeEdit action to apply to the stroke resolved from click selection, or to the current stored subset selection for split-by-selection.",
            "preset:Rename",
            0,
            "preset:Delete",
            1,
            "preset:Move",
            2,
            "preset:Merge",
            3,
            "preset:SplitBySelection",
            4,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Stroke Edit",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "isStrokeEdit",
        ],
        "strokeMoveToIndex": [
            "description",
            "Target sibling order index applied by StrokeEdit when strokeEditAction is Move.",
            "label",
            "Stroke Index",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "strokeMove",
        ],
        "strokeMergeTarget": [
            "description",
            "Target stroke name used by StrokeEdit when strokeEditAction is Merge.",
            "label",
            "Merge Target",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            150,
            "toolbarLayout:visibilityActivator",
            "strokeMerge",
        ],
        "layerEditAction": [
            "description",
            "LayerEdit action to apply to the layer resolved from the current click selection.",
            "preset:Rename",
            0,
            "preset:SetVisible",
            1,
            "preset:SetMute",
            2,
            "preset:SetSolo",
            3,
            "preset:SetTimeRange",
            4,
            "preset:Move",
            5,
            "preset:SetMode",
            6,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Layer Edit",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "isLayerEdit",
        ],
        "layerVisible": [
            "description",
            "Visible value applied by LayerEdit when layerEditAction is SetVisible.",
            "label",
            "Visible",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            80,
            "toolbarLayout:visibilityActivator",
            "layerSetVisible",
        ],
        "layerMute": [
            "description",
            "Mute value applied by LayerEdit when layerEditAction is SetMute.",
            "layout:visibilityActivator",
            False,
        ],
        "layerSolo": [
            "description",
            "Solo value applied by LayerEdit when layerEditAction is SetSolo.",
            "layout:visibilityActivator",
            False,
        ],
        "layerFrameStart": [
            "description",
            "Frame start applied by LayerEdit when layerEditAction is SetTimeRange.",
            "layout:visibilityActivator",
            False,
        ],
        "layerFrameEnd": [
            "description",
            "Frame end applied by LayerEdit when layerEditAction is SetTimeRange.",
            "layout:visibilityActivator",
            False,
        ],
        "layerMoveToIndex": [
            "description",
            "Target sibling order index applied by LayerEdit when layerEditAction is Move.",
            "label",
            "Layer Index",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "layerMove",
        ],
        "layerMode": [
            "description",
            "Frame mode applied by LayerEdit when layerEditAction is SetMode. This updates the selected layer and the currently selected stroke when one is resolved.",
            "preset:Persistent",
            0,
            "preset:Additive",
            1,
            "preset:Override",
            2,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "layout:visibilityActivator",
            False,
        ],
        "brushSize": [
            "description",
            "Brush radius for paint, erase, brush selection, relax, and reproject interactions.",
            "label",
            "Size",
            "toolbarLayout:section",
            "Bottom",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "usesBrushRadius",
        ],
        "points": [
            "description",
            "Mirrors PaintedPoints.brushDefaults.points so paint mode can control how many points each dab spawns before density scaling.",
            "label",
            "Points",
            "toolbarLayout:section",
            "Bottom",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "isPaint",
        ],
        "density": [
            "description",
            "Relative paint density for brush-based point creation.",
            "label",
            "Density",
            "toolbarLayout:section",
            "Bottom",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "isPaint",
        ],
        "softness": [
            "description",
            "Brush falloff softness for paint and erase.",
            "label",
            "Softness",
            "toolbarLayout:section",
            "Bottom",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "usesBrushFalloff",
        ],
        "spacing": [
            "description",
            "Relative spacing multiplier used by compiled drag sampling and stroke densification.",
            "label",
            "Spacing",
            "toolbarLayout:section",
            "Bottom",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "usesBrushSpacing",
        ],
        "frameMode": [
            "description",
            "Frame mode used by LayerEdit when applying SetMode. Top-level HUD frame mode affordance.",
            "preset:Persistent",
            0,
            "preset:Additive",
            1,
            "preset:Override",
            2,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Frame Mode",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "layerSetMode",
        ],
        "frameStart": [
            "description",
            "Frame start used by LayerEdit when applying SetTimeRange. Top-level HUD frame start affordance.",
            "label",
            "Start",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            70,
            "toolbarLayout:visibilityActivator",
            "layerSetTimeRange",
        ],
        "frameEnd": [
            "description",
            "Frame end used by LayerEdit when applying SetTimeRange. Top-level HUD frame end affordance.",
            "label",
            "End",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            70,
            "toolbarLayout:visibilityActivator",
            "layerSetTimeRange",
        ],
        "muteBehavior": [
            "description",
            "Mute state used by LayerEdit when applying SetMute. Top-level HUD mute behavior affordance.",
            "label",
            "Mute",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            70,
            "toolbarLayout:visibilityActivator",
            "layerSetMute",
        ],
        "soloBehavior": [
            "description",
            "Solo state used by LayerEdit when applying SetSolo. Top-level HUD solo behavior affordance.",
            "label",
            "Solo",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            70,
            "toolbarLayout:visibilityActivator",
            "layerSetSolo",
        ],
        "relaxObjective": [
            "description",
            "Relax objective mirrored from the targeted PaintedPoints node so the tool can reuse the standard preset widget for preserve-silhouette or even-redistribution smoothing.",
            "preset:Preserve Silhouette",
            0,
            "preset:Even Redistribution",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Relax",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "isRelax",
        ],
        "targetFilter": [
            "description",
            "Mirrors PaintedPoints.targetFilter so the tool reuses the standard target filter control on the active node.",
            "label",
            "Target",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            140,
            "toolbarLayout:visibilityActivator",
            "usesTargetFilters",
        ],
        "targetSetFilter": [
            "description",
            "Mirrors PaintedPoints.targetSetFilter so the tool reuses the standard target set filter control on the active node.",
            "label",
            "Target Set",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            140,
            "toolbarLayout:visibilityActivator",
            "usesTargetFilters",
        ],
        "surfaceMode": [
            "description",
            "Mirrors PaintedPoints.surfaceMode so the tool reuses the standard surface-basis preset widget.",
            "preset:Viewport Mesh",
            0,
            "preset:Pre-Subdiv Cage",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Surface",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "usesSurfaceMode",
        ],
        "paintThroughMode": [
            "description",
            "Mirrors PaintedPoints.paintThroughMode so the tool reuses the standard paint-through preset widget.",
            "preset:Front Most Only",
            0,
            "preset:Filtered Brush Volume",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Paint Through",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            130,
            "toolbarLayout:visibilityActivator",
            "isPaint",
        ],
        "globalModePrecedence": [
            "description",
            "Mirrors PaintedPoints.globalModePrecedence so the tool reuses the standard layer-vs-stroke precedence preset widget.",
            "preset:Stroke Wins",
            0,
            "preset:Layer Wins",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Precedence",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "isPaint",
        ],
        "pressureDefaultsEnabled": [
            "description",
            "Mirrors PaintedPoints.pressureDefaults.enabled so the tool reuses the standard pressure enable control.",
            "label",
            "Pressure",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            80,
            "toolbarLayout:visibilityActivator",
            "usesPressure",
        ],
        "pressureDefaultsMappingMode": [
            "description",
            "Mirrors PaintedPoints.pressureDefaults.mappingMode so the tool reuses the standard pressure mapping preset widget.",
            "preset:Direct",
            0,
            "preset:Curve",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Pressure Map",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "usesPressure",
        ],
        "pressureDefaultsDensityCurve": [
            "description",
            "Mirrors PaintedPoints.pressureDefaults.densityCurve so the tool exposes the existing density pressure curve data on the active node.",
            "layout:visibilityActivator",
            False,
        ],
        "pressureDefaultsSoftnessCurve": [
            "description",
            "Mirrors PaintedPoints.pressureDefaults.softnessCurve so the tool exposes the existing softness pressure curve data on the active node.",
            "layout:visibilityActivator",
            False,
        ],
        "eraseSpace": [
            "description",
            "Selects whether Erase matches authored points in visible/world brush space on the hit surface, or across attachment-space samples.",
            "preset:Visible Space",
            0,
            "preset:Attachment Space",
            1,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Erase Space",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            120,
            "toolbarLayout:visibilityActivator",
            "isErase",
        ],
        "pressureValue": [
            "description",
            "Pressure sample used by compiled paint authoring when pressure defaults are enabled. Direct mapping uses the raw value, while Curve mode currently applies a simple squared response.",
            "label",
            "Pressure Value",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            90,
            "toolbarLayout:visibilityActivator",
            "usesPressure",
        ],
        "rotationMode": [
            "description",
            "Mirrors PaintedPoints.brushDefaults.rotationMode so the tool reuses the brush rotation preset widget.",
            "preset:None",
            0,
            "preset:Per-Point",
            1,
            "preset:Random",
            2,
            "plugValueWidget:type",
            "GafferUI.PresetsPlugValueWidget",
            "label",
            "Rotation",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            110,
            "toolbarLayout:visibilityActivator",
            "usesBrushRadius",
        ],
        "scaleJitter": [
            "description",
            "Mirrors PaintedPoints.brushDefaults.scaleJitter so the tool exposes the random scale variation control on the active node.",
            "label",
            "Scale Jitter",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            110,
            "toolbarLayout:visibilityActivator",
            "usesBrushRadius",
        ],
        "widthJitter": [
            "description",
            "Mirrors PaintedPoints.brushDefaults.widthJitter so the tool exposes the random width variation control on the active node.",
            "label",
            "Width Jitter",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            110,
            "toolbarLayout:visibilityActivator",
            "usesBrushRadius",
        ],
        "previewCount": [
            "description",
            "Internal preview count used by legacy test scaffolding.",
            "label",
            "Preview",
            "toolbarLayout:section",
            "Right",
            "toolbarLayout:width",
            80,
            "toolbarLayout:visibilityActivator",
            False,
        ],
        "status": [
            "description",
            "Latest tool action result, including pressure-aware Paint, filtered brush-volume paint-through, brush Erase space behavior, SelectBrush, SelectLasso marquee subset selection, Relax, Reproject, LayerEdit rename/state/move/set-mode actions, and StrokeEdit rename/delete/move/merge/split status.",
        ],
        "active": [
            "description",
            "Enables the interactive paint/erase/select/edit viewport tool, including pressure-aware paint authoring, filtered brush-volume paint-through, brush Erase space behavior, marquee selection, Relax/Reproject selection actions, LayerEdit rename/state/move/set-mode actions, and StrokeEdit rename/delete/move/merge/split actions.",
            "layout:section",
            "Tool",
            "boolPlugValueWidget:image",
            _tool_icon,
        ],
    },
)
