from pathlib import Path

import Gaffer

import GafferPointCloudPlus


def _documentation_url(page_name):
    path = Path(__file__).resolve().parents[2] / "docs" / "html" / page_name
    return path.as_uri() if path.exists() else None


if GafferPointCloudPlus.PointCloudPlus is not None:
    Gaffer.Metadata.registerNode(
        GafferPointCloudPlus.PointCloudPlus,
        "description",
        "Wrapper node for point-cloud generation, cleanup, and output workflows.",
        "documentation:url",
        lambda node: _documentation_url("PointCloudPlus.html"),
        "layout:activator:isGeometryMode",
        lambda node: node["mode"].getValue() == 0,
        "layout:activator:isFileMode",
        lambda node: node["mode"].getValue() == 1,
        "layout:activator:isRandomDistribution",
        lambda node: node["distribution"].getValue() == 0,
        plugs={
            "outputLocation": [
                "description",
                "Scene location where the generated or copied points object will be emitted.",
                "layout:section",
                "Output",
            ],
            "pointType": [
                "description",
                "Requested output point type written as the constant type primvar.",
                "layout:section",
                "Output",
            ],
            "mode": [
                "description",
                "Selects whether PointCloudPlus generates points from geometry or copies an existing input points object.",
                "preset:Geometry",
                0,
                "preset:File",
                1,
                "plugValueWidget:type",
                "GafferUI.PresetsPlugValueWidget",
                "layout:section",
                "Settings",
            ],
            "filter": [
                "description",
                "Location filter used to find support geometry in Geometry mode.",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "distribution": [
                "description",
                "Point distribution mode used in Geometry mode.",
                "preset:Random",
                0,
                "preset:Primitive Center",
                1,
                "plugValueWidget:type",
                "GafferUI.PresetsPlugValueWidget",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "useDensity": [
                "description",
                "When enabled, derives point count from density instead of the explicit pointCount plug.",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "density": [
                "description",
                "Simple density multiplier used by the MVP geometry mode.",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "pointCount": [
                "description",
                "Explicit point count used by random geometry generation when useDensity is off.",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "distributionSeed": [
                "description",
                "Deterministic random seed used by geometry point generation.",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "jittering": [
                "description",
                "Additional point offset used by the MVP geometry generators.",
                "layout:section",
                "Geometry",
                "layout:activator",
                "isGeometryMode",
            ],
            "primPath": [
                "description",
                "Path to the existing input points object that should be copied in File mode.",
                "layout:section",
                "File",
                "layout:activator",
                "isFileMode",
            ],
            "fileName": [
                "description",
                "Reserved for later external file-backed point-cloud import. Not used in the current MVP.",
                "layout:section",
                "Advanced",
                "layout:activator",
                "isFileMode",
                "plugValueWidget:type",
                "",
                "nodule:type",
                "",
            ],
            "purpose": [
                "description",
                "Reserved for later USD/Alembic-style purpose filtering. Not used in the current MVP.",
                "layout:section",
                "Advanced",
                "layout:activator",
                "isFileMode",
                "plugValueWidget:type",
                "",
                "nodule:type",
                "",
            ],
            "frameOffset": [
                "description",
                "Additional offset applied to the copied input scene evaluation frame in File mode.",
                "layout:section",
                "File",
                "layout:activator",
                "isFileMode",
            ],
            "frame": [
                "description",
                "Base evaluation frame used by File mode playback controls.",
                "layout:section",
                "File",
                "layout:activator",
                "isFileMode",
            ],
            "animationBehavior": [
                "description",
                "Hold freezes File mode to frame + frameOffset. Repeat follows the current context frame with frame and frameOffset applied as offsets.",
                "preset:Hold",
                0,
                "preset:Repeat",
                1,
                "plugValueWidget:type",
                "GafferUI.PresetsPlugValueWidget",
                "layout:section",
                "File",
                "layout:activator",
                "isFileMode",
                "nodule:type",
                "",
            ],
        },
    )
