name: Linux Toolset Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Build toolset
        env:
          IMAGE_NAME: d3smond/scatter-paint-tools-gaffer-build:gaffer-1.6.18.0
        run: ./build-plugins.sh --plugin all --pull
